CC = gcc
CFLAGS = -g -Wall
PROGRAMS = 01-reverse_string 02-string_length 03-series_of_letters 04-count_substring_occurrences 05-text_filter 06-palindromes 07-implement_a_string_copy_function 08-implement_a_string_concatenation_function 09-implement_a_word_count_function 10-implement_a_string_length_function 11-implement_a_string_search_function 12-implement_a_substring_function 13-read_line_function 14-matrix_of_palindromes 15-remove_names 16-longest_word_in_text 17-xml_parser 18-longest_area_in_array

all: $(PROGRAMS)

01-reverse_string: 01-reverse_string.c homework_tools.c
	$(CC) $(CFLAGS) -o $@ $<

02-string_length: 02-string_length.c
	$(CC) $(CFLAGS) -o $@ $<

03-series_of_letters: 03-series_of_letters.c homework_tools.c
	$(CC) $(CFLAGS) -o $@ $<

04-count_substring_occurrences: 04-count_substring_occurrences.c homework_tools.c
	$(CC) $(CFLAGS) -o $@ $<

05-text_filter: 05-text_filter.c homework_tools.c
	$(CC) $(CFLAGS) -o $@ $<

06-palindromes: 06-palindromes.c homework_tools.c
	$(CC) $(CFLAGS) -o $@ $<

07-implement_a_string_copy_function: 07-implement_a_string_copy_function.c
	$(CC) $(CFLAGS) -o $@ $<

08-implement_a_string_concatenation_function: 08-implement_a_string_concatenation_function.c
	$(CC) $(CFLAGS) -o $@ $<

09-implement_a_word_count_function: 09-implement_a_word_count_function.c
	$(CC) $(CFLAGS) -o $@ $<

10-implement_a_string_length_function: 10-implement_a_string_length_function.c
	$(CC) $(CFLAGS) -o $@ $<

11-implement_a_string_search_function: 11-implement_a_string_search_function.c
	$(CC) $(CFLAGS) -o $@ $<

12-implement_a_substring_function: 12-implement_a_substring_function.c homework_tools.c
	$(CC) $(CFLAGS) -o $@ $<

13-read_line_function: 13-read_line_function.c
	$(CC) $(CFLAGS) -o $@ $<

14-matrix_of_palindromes: 14-matrix_of_palindromes.c
	$(CC) $(CFLAGS) -o $@ $<

15-remove_names: 15-remove_names.c
	$(CC) $(CFLAGS) -o $@ $<

16-longest_word_in_text: 16-longest_word_in_text.c
	$(CC) $(CFLAGS) -o $@ $<

17-xml_parser: 17-xml_parser.c
	$(CC) $(CFLAGS) -o $@ $<

18-longest_area_in_array: 18-longest_area_in_array.c
	$(CC) $(CFLAGS) -o $@ $<

clean:
	$(RM) $(PROGRAMS)
