CC = gcc
CFLAGS = -g -Wall
PROGRAMS = 01-save_and_print_numbers_in_range 02-linear_search 03-sort_array_of_numbers 04-categorize_numbers 05-longest_increasing_sequence 06-join_lists 07-reverse_array 08-iterative_binary_search 09-recursive_binary_search 10-numbers_beneath_main_diagonal 11-scalar_multiplication_of_a_vector 12-dot_product_of_vectors 13-cross_product_of_vectors 14-sum_of_matrices 15-multiplication_of_matrices 16-text_gravity 17-text_bombardment

all: $(PROGRAMS)

01-save_and_print_numbers_in_range: 01-save_and_print_numbers_in_range.c homework_tools.c
	$(CC) $(CFLAGS) -o $@ $<

02-linear_search: 02-linear_search.c homework_tools.c
	$(CC) $(CFLAGS) -o $@ $<

03-sort_array_of_numbers: 03-sort_array_of_numbers.c homework_tools.c
	$(CC) $(CFLAGS) -o $@ $<

04-categorize_numbers: 04-categorize_numbers.c homework_tools.c
	$(CC) $(CFLAGS) -o $@ $<

05-longest_increasing_sequence: 05-longest_increasing_sequence.c homework_tools.c
	$(CC) $(CFLAGS) -o $@ $<

06-join_lists: 06-join_lists.c homework_tools.c
	$(CC) $(CFLAGS) -o $@ $<

07-reverse_array: 07-reverse_array.c homework_tools.c
	$(CC) $(CFLAGS) -o $@ $<

08-iterative_binary_search: 08-iterative_binary_search.c homework_tools.c
	$(CC) $(CFLAGS) -o $@ $<

09-recursive_binary_search: 09-recursive_binary_search.c homework_tools.c
	$(CC) $(CFLAGS) -o $@ $<

10-numbers_beneath_main_diagonal: 10-numbers_beneath_main_diagonal.c homework_tools.c
	$(CC) $(CFLAGS) -o $@ $<

11-scalar_multiplication_of_a_vector: 11-scalar_multiplication_of_a_vector.c homework_tools.c
	$(CC) $(CFLAGS) -o $@ $<

12-dot_product_of_vectors: 12-dot_product_of_vectors.c homework_tools.c
	$(CC) $(CFLAGS) -o $@ $<

13-cross_product_of_vectors: 13-cross_product_of_vectors.c homework_tools.c
	$(CC) $(CFLAGS) -o $@ $<

14-sum_of_matrices: 14-sum_of_matrices.c homework_tools.c
	$(CC) $(CFLAGS) -o $@ $<

15-multiplication_of_matrices: 15-multiplication_of_matrices.c homework_tools.c
	$(CC) $(CFLAGS) -o $@ $<

16-text_gravity: 16-text_gravity.c homework_tools.c
	$(CC) $(CFLAGS) -o $@ $<

17-text_bombardment: 17-text_bombardment.c homework_tools.c
	$(CC) $(CFLAGS) -o $@ $<

clean:
	$(RM) $(PROGRAMS)
