CC = gcc
CFLAGS = -g -Wall
PROGRAMS = 01-declare_variables 02-float_or_double 03-variable_in_hexadecimal_format 04-gender 05-names 06-quotes_in_strings 07-exchange_variable_values 08-employee_data 09-back_account_data 10-comparing_floats 11-print_the_ascii_table

all: $(PROGRAMS)

01-declare_variables: 01-declare_variables.c
	$(CC) $(CFLAGS) -o $@ $<

02-float_or_double: 02-float_or_double.c
	$(CC) $(CFLAGS) -o $@ $<

03-variable_in_hexadecimal_format: 03-variable_in_hexadecimal_format.c
	$(CC) $(CFLAGS) -o $@ $<

04-gender: 04-gender.c
	$(CC) $(CFLAGS) -o $@ $<

05-names: 05-names.c
	$(CC) $(CFLAGS) -o $@ $<

06-quotes_in_strings: 06-quotes_in_strings.c
	$(CC) $(CFLAGS) -o $@ $<

07-exchange_variable_values: 07-exchange_variable_values.c
	$(CC) $(CFLAGS) -o $@ $<

08-employee_data: 08-employee_data.c
	$(CC) $(CFLAGS) -o $@ $<

09-back_account_data: 09-back_account_data.c
	$(CC) $(CFLAGS) -o $@ $<

10-comparing_floats: 10-comparing_floats.c
	$(CC) $(CFLAGS) -o $@ $<

11-print_the_ascii_table: 11-print_the_ascii_table.c
	$(CC) $(CFLAGS) -o $@ $<

clean:
	$(RM) $(PROGRAMS)
