CC = gcc
CFLAGS = -g -Wall
PROGRAMS = 01-odd_and_even_integers 02-big_and_odd 03-pure_divisor 04-gravitation_on_the_moon 05-divide_by_7_and_5 06-rectangles 07-average_sum 08-third_digit_is_7 09-four_digit_number 10-nth_digit 11-point_in_a_circle 12-prime_number_check 13-trapezoids 14-point_inside_a_circle_and_outside_of_a_reactangle

all: $(PROGRAMS)

01-odd_and_even_integers: 01-odd_and_even_integers.c
	$(CC) $(CFLAGS) -o $@ $<

02-big_and_odd: 02-big_and_odd.c
	$(CC) $(CFLAGS) -o $@ $<

03-pure_divisor: 03-pure_divisor.c
	$(CC) $(CFLAGS) -o $@ $<

04-gravitation_on_the_moon: 04-gravitation_on_the_moon.c
	$(CC) $(CFLAGS) -o $@ $<

05-divide_by_7_and_5: 05-divide_by_7_and_5.c
	$(CC) $(CFLAGS) -o $@ $<

06-rectangles: 06-rectangles.c
	$(CC) $(CFLAGS) -o $@ $<

07-average_sum: 07-average_sum.c
	$(CC) $(CFLAGS) -o $@ $<

08-third_digit_is_7: 08-third_digit_is_7.c
	$(CC) $(CFLAGS) -o $@ $<

09-four_digit_number: 09-four_digit_number.c
	$(CC) $(CFLAGS) -o $@ $<

10-nth_digit: 10-nth_digit.c
	$(CC) $(CFLAGS) -o $@ $<

11-point_in_a_circle: 11-point_in_a_circle.c
	$(CC) $(CFLAGS) -o $@ $<

12-prime_number_check: 12-prime_number_check.c
	$(CC) $(CFLAGS) -o $@ $<

13-trapezoids: 13-trapezoids.c
	$(CC) $(CFLAGS) -o $@ $<

14-point_inside_a_circle_and_outside_of_a_reactangle: 14-point_inside_a_circle_and_outside_of_a_reactangle.c
	$(CC) $(CFLAGS) -o $@ $<

clean:
	$(RM) $(PROGRAMS)
