CC = gcc
CFLAGS = -g -Wall
PROGRAMS = 01-numbers_from_1_to_n 02-numbers_not_divisible_by_3_and_7 03-min_max_sum_average_of_n_numbers 04-print_a_deck_of_52_cards 05-calculate_factorials_1 06-calculate_factorials_2 07-calculate_factorials_3 08-catalan_numbers 09-matrix_of_numbers 10-odd_and_even_product 11-random_numbers_in_given_range 12-randomize_the_numbers_1_to_n 13-binary_to_decimal_number 14-decimal_to_binary_number 15-hexadecimal_to_decimal_number 16-decimal_to_hexadecimal_number 17-calculate_gcd 19-spiral_matrix 18-trailing_zeros_in_factorial 19-spiral_matrix_animated

all: $(PROGRAMS)

01-numbers_from_1_to_n: 01-numbers_from_1_to_n.c
	$(CC) $(CFLAGS) -o $@ $<

02-numbers_not_divisible_by_3_and_7: 02-numbers_not_divisible_by_3_and_7.c
	$(CC) $(CFLAGS) -o $@ $<

03-min_max_sum_average_of_n_numbers: 03-min_max_sum_average_of_n_numbers.c
	$(CC) $(CFLAGS) -o $@ $<

04-print_a_deck_of_52_cards: 04-print_a_deck_of_52_cards.c
	$(CC) $(CFLAGS) -o $@ $<

05-calculate_factorials_1: 05-calculate_factorials_1.c
	$(CC) $(CFLAGS) -o $@ $<

06-calculate_factorials_2: 06-calculate_factorials_2.c
	$(CC) $(CFLAGS) -o $@ $<

07-calculate_factorials_3: 07-calculate_factorials_3.c
	$(CC) $(CFLAGS) -o $@ $<

08-catalan_numbers: 08-catalan_numbers.c
	$(CC) $(CFLAGS) -o $@ $<

09-matrix_of_numbers: 09-matrix_of_numbers.c
	$(CC) $(CFLAGS) -o $@ $<

10-odd_and_even_product: 10-odd_and_even_product.c
	$(CC) $(CFLAGS) -o $@ $<

11-random_numbers_in_given_range: 11-random_numbers_in_given_range.c
	$(CC) $(CFLAGS) -o $@ $<

12-randomize_the_numbers_1_to_n: 12-randomize_the_numbers_1_to_n.c
	$(CC) $(CFLAGS) -o $@ $<

13-binary_to_decimal_number: 13-binary_to_decimal_number.c
	$(CC) $(CFLAGS) -o $@ $<

14-decimal_to_binary_number: 14-decimal_to_binary_number.c
	$(CC) $(CFLAGS) -o $@ $<

15-hexadecimal_to_decimal_number: 15-hexadecimal_to_decimal_number.c
	$(CC) $(CFLAGS) -o $@ $<

16-decimal_to_hexadecimal_number: 16-decimal_to_hexadecimal_number.c
	$(CC) $(CFLAGS) -o $@ $<

17-calculate_gcd: 17-calculate_gcd.c
	$(CC) $(CFLAGS) -o $@ $<

18-trailing_zeros_in_factorial: 18-trailing_zeros_in_factorial.c
	$(CC) $(CFLAGS) -o $@ $<

19-spiral_matrix: 19-spiral_matrix.c
	$(CC) $(CFLAGS) -o $@ $<

19-spiral_matrix_animated: 19-spiral_matrix_animated.c
	$(CC) $(CFLAGS) -o $@ $<

clean:
	$(RM) $(PROGRAMS)
