CC = gcc
CFLAGS = -g -Wall
PROGRAMS = 01-exchange_if_greater 02-bonus_score 03-check_for_a_play_card 04-multiplication_sign 05-the_biggest_of_3_numbers 06-the_biggest_of_5_numbers 07-sort_3_numbers_with_nested_ifs 08-digit_as_a_word 09-play_with_int_double_and_string 10-beer_time 11-numbers_as_words 12-zero_subset

all: $(PROGRAMS)

01-exchange_if_greater: 01-exchange_if_greater.c
	$(CC) $(CFLAGS) -o $@ $<

02-bonus_score: 02-bonus_score.c
	$(CC) $(CFLAGS) -o $@ $<

03-check_for_a_play_card: 03-check_for_a_play_card.c
	$(CC) $(CFLAGS) -o $@ $<

04-multiplication_sign: 04-multiplication_sign.c
	$(CC) $(CFLAGS) -o $@ $<

05-the_biggest_of_3_numbers: 05-the_biggest_of_3_numbers.c
	$(CC) $(CFLAGS) -o $@ $<

06-the_biggest_of_5_numbers: 06-the_biggest_of_5_numbers.c
	$(CC) $(CFLAGS) -o $@ $<

07-sort_3_numbers_with_nested_ifs: 07-sort_3_numbers_with_nested_ifs.c
	$(CC) $(CFLAGS) -o $@ $<

08-digit_as_a_word: 08-digit_as_a_word.c
	$(CC) $(CFLAGS) -o $@ $<

09-play_with_int_double_and_string: 09-play_with_int_double_and_string.c
	$(CC) $(CFLAGS) -o $@ $<

10-beer_time: 10-beer_time.c
	$(CC) $(CFLAGS) -o $@ $<

11-numbers_as_words: 11-numbers_as_words.c
	$(CC) $(CFLAGS) -o $@ $<

12-zero_subset: 12-zero_subset.c
	$(CC) $(CFLAGS) -o $@ $<

clean:
	$(RM) $(PROGRAMS)
