CC = gcc
CFLAGS = -g -Wall
PROGRAMS = 01-sum_3_numbers 02-print_company_information 03-circle_perimeter_and_area 04-formatting_numbers 05-sum_5_numbers 06-numbers_from_1_to_n 07-sum_of_n_numbers 08-fibonacci_numbers 09-numbers_in_interval_dividable_by_given_number

all: $(PROGRAMS)

01-sum_3_numbers: 01-sum_3_numbers.c
	$(CC) $(CFLAGS) -o $@ $<

02-print_company_information: 02-print_company_information.c
	$(CC) $(CFLAGS) -o $@ $<

03-circle_perimeter_and_area: 03-circle_perimeter_and_area.c
	$(CC) $(CFLAGS) -o $@ $<

04-formatting_numbers: 04-formatting_numbers.c
	$(CC) $(CFLAGS) -o $@ $<

05-sum_5_numbers: 05-sum_5_numbers.c
	$(CC) $(CFLAGS) -o $@ $<

06-numbers_from_1_to_n: 06-numbers_from_1_to_n.c
	$(CC) $(CFLAGS) -o $@ $<

07-sum_of_n_numbers: 07-sum_of_n_numbers.c
	$(CC) $(CFLAGS) -o $@ $<

08-fibonacci_numbers: 08-fibonacci_numbers.c
	$(CC) $(CFLAGS) -o $@ $<

09-numbers_in_interval_dividable_by_given_number: 09-numbers_in_interval_dividable_by_given_number.c
	$(CC) $(CFLAGS) -o $@ $<

clean:
	$(RM) $(PROGRAMS)
